-- Creating User table
CREATE TABLE USERS (
    USER_ID BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255)
);

-- Creating Task table
CREATE TABLE TASKS (
    TASK_ID BIGINT PRIMARY KEY,
    TASK_NAME VARCHAR(255),
    USER_ID BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
